- title: "Reclaim Your Life (Book)"
  desc: "Core framework for exiting burnout and reclaiming your life."
  format: "PDF"
  status: "Available"
  url: "https://payhip.com/b/Cj98m"

- - title: "Reclaim Your Time (Workbook)"
  desc: "Workbook"
  format: "PDF"
  status: "Available"
  url: "https://payhip.com/b/VbCpf"
