- title: "Reclaim Your Life (Book)"
  desc: "Core framework for exiting burnout systems."
  format: "PDF"
  status: "Available"
  url: "https://example.com"

- title: "Panic-Moment Finance Decision Tool"
  desc: "What to pay when you can’t pay everything."
  format: "PDF"
  status: "New"
  url: "https://example.com"

